// Full world country list for the PATIENT phone picker — patients are
// accepted from anywhere regardless of dial code, unlike practitioners/
// organizations whose country picker is restricted to the admin-managed
// `allowed_countries` whitelist (managed from the web admin at /admin/countries).
export interface WorldCountry {
  iso2: string
  dial: string
  name: string
}

export function flagEmoji(iso2: string): string {
  return iso2
    .toUpperCase()
    .replace(/./g, c => String.fromCodePoint(0x1f1e6 - 65 + c.charCodeAt(0)))
}

export const WORLD_COUNTRIES: WorldCountry[] = [
  { iso2: 'SN', dial: '+221', name: 'Sénégal' },
  { iso2: 'CI', dial: '+225', name: "Côte d'Ivoire" },
  { iso2: 'ML', dial: '+223', name: 'Mali' },
  { iso2: 'CM', dial: '+237', name: 'Cameroun' },
  { iso2: 'GN', dial: '+224', name: 'Guinée' },
  { iso2: 'BF', dial: '+226', name: 'Burkina Faso' },
  { iso2: 'BJ', dial: '+229', name: 'Bénin' },
  { iso2: 'TG', dial: '+228', name: 'Togo' },
  { iso2: 'NE', dial: '+227', name: 'Niger' },
  { iso2: 'MR', dial: '+222', name: 'Mauritanie' },
  { iso2: 'GA', dial: '+241', name: 'Gabon' },
  { iso2: 'CD', dial: '+243', name: 'RD Congo' },
  { iso2: 'CG', dial: '+242', name: 'Congo' },
  { iso2: 'GW', dial: '+245', name: 'Guinée-Bissau' },
  { iso2: 'GM', dial: '+220', name: 'Gambie' },
  { iso2: 'CV', dial: '+238', name: 'Cap-Vert' },
  { iso2: 'SL', dial: '+232', name: 'Sierra Leone' },
  { iso2: 'LR', dial: '+231', name: 'Liberia' },
  { iso2: 'GH', dial: '+233', name: 'Ghana' },
  { iso2: 'NG', dial: '+234', name: 'Nigeria' },
  { iso2: 'TD', dial: '+235', name: 'Tchad' },
  { iso2: 'CF', dial: '+236', name: 'Centrafrique' },
  { iso2: 'GQ', dial: '+240', name: 'Guinée Équatoriale' },
  { iso2: 'AO', dial: '+244', name: 'Angola' },
  { iso2: 'MZ', dial: '+258', name: 'Mozambique' },
  { iso2: 'ZM', dial: '+260', name: 'Zambie' },
  { iso2: 'MG', dial: '+261', name: 'Madagascar' },
  { iso2: 'RE', dial: '+262', name: 'Réunion' },
  { iso2: 'ZW', dial: '+263', name: 'Zimbabwe' },
  { iso2: 'NA', dial: '+264', name: 'Namibie' },
  { iso2: 'MW', dial: '+265', name: 'Malawi' },
  { iso2: 'LS', dial: '+266', name: 'Lesotho' },
  { iso2: 'BW', dial: '+267', name: 'Botswana' },
  { iso2: 'SZ', dial: '+268', name: 'Eswatini' },
  { iso2: 'KM', dial: '+269', name: 'Comores' },
  { iso2: 'ZA', dial: '+27',  name: 'Afrique du Sud' },
  { iso2: 'ET', dial: '+251', name: 'Éthiopie' },
  { iso2: 'DJ', dial: '+253', name: 'Djibouti' },
  { iso2: 'SO', dial: '+252', name: 'Somalie' },
  { iso2: 'KE', dial: '+254', name: 'Kenya' },
  { iso2: 'TZ', dial: '+255', name: 'Tanzanie' },
  { iso2: 'UG', dial: '+256', name: 'Ouganda' },
  { iso2: 'BI', dial: '+257', name: 'Burundi' },
  { iso2: 'RW', dial: '+250', name: 'Rwanda' },
  { iso2: 'SS', dial: '+211', name: 'Soudan du Sud' },
  { iso2: 'SD', dial: '+249', name: 'Soudan' },
  { iso2: 'ER', dial: '+291', name: 'Érythrée' },
  { iso2: 'EG', dial: '+20',  name: 'Égypte' },
  { iso2: 'LY', dial: '+218', name: 'Libye' },
  { iso2: 'TN', dial: '+216', name: 'Tunisie' },
  { iso2: 'DZ', dial: '+213', name: 'Algérie' },
  { iso2: 'MA', dial: '+212', name: 'Maroc' },
  { iso2: 'FR', dial: '+33',  name: 'France' },
  { iso2: 'BE', dial: '+32',  name: 'Belgique' },
  { iso2: 'CH', dial: '+41',  name: 'Suisse' },
  { iso2: 'LU', dial: '+352', name: 'Luxembourg' },
  { iso2: 'DE', dial: '+49',  name: 'Allemagne' },
  { iso2: 'GB', dial: '+44',  name: 'Royaume-Uni' },
  { iso2: 'IE', dial: '+353', name: 'Irlande' },
  { iso2: 'NL', dial: '+31',  name: 'Pays-Bas' },
  { iso2: 'ES', dial: '+34',  name: 'Espagne' },
  { iso2: 'PT', dial: '+351', name: 'Portugal' },
  { iso2: 'IT', dial: '+39',  name: 'Italie' },
  { iso2: 'AT', dial: '+43',  name: 'Autriche' },
  { iso2: 'SE', dial: '+46',  name: 'Suède' },
  { iso2: 'NO', dial: '+47',  name: 'Norvège' },
  { iso2: 'DK', dial: '+45',  name: 'Danemark' },
  { iso2: 'FI', dial: '+358', name: 'Finlande' },
  { iso2: 'PL', dial: '+48',  name: 'Pologne' },
  { iso2: 'GR', dial: '+30',  name: 'Grèce' },
  { iso2: 'RO', dial: '+40',  name: 'Roumanie' },
  { iso2: 'TR', dial: '+90',  name: 'Turquie' },
  { iso2: 'RU', dial: '+7',   name: 'Russie' },
  { iso2: 'UA', dial: '+380', name: 'Ukraine' },
  { iso2: 'CA', dial: '+1',   name: 'Canada' },
  { iso2: 'US', dial: '+1',   name: 'États-Unis' },
  { iso2: 'MX', dial: '+52',  name: 'Mexique' },
  { iso2: 'BR', dial: '+55',  name: 'Brésil' },
  { iso2: 'AR', dial: '+54',  name: 'Argentine' },
  { iso2: 'CO', dial: '+57',  name: 'Colombie' },
  { iso2: 'CL', dial: '+56',  name: 'Chili' },
  { iso2: 'PE', dial: '+51',  name: 'Pérou' },
  { iso2: 'HT', dial: '+509', name: 'Haïti' },
  { iso2: 'CN', dial: '+86',  name: 'Chine' },
  { iso2: 'JP', dial: '+81',  name: 'Japon' },
  { iso2: 'KR', dial: '+82',  name: 'Corée du Sud' },
  { iso2: 'IN', dial: '+91',  name: 'Inde' },
  { iso2: 'PK', dial: '+92',  name: 'Pakistan' },
  { iso2: 'BD', dial: '+880', name: 'Bangladesh' },
  { iso2: 'ID', dial: '+62',  name: 'Indonésie' },
  { iso2: 'MY', dial: '+60',  name: 'Malaisie' },
  { iso2: 'SG', dial: '+65',  name: 'Singapour' },
  { iso2: 'TH', dial: '+66',  name: 'Thaïlande' },
  { iso2: 'VN', dial: '+84',  name: 'Vietnam' },
  { iso2: 'PH', dial: '+63',  name: 'Philippines' },
  { iso2: 'SA', dial: '+966', name: 'Arabie Saoudite' },
  { iso2: 'AE', dial: '+971', name: 'Émirats Arabes Unis' },
  { iso2: 'QA', dial: '+974', name: 'Qatar' },
  { iso2: 'KW', dial: '+965', name: 'Koweït' },
  { iso2: 'LB', dial: '+961', name: 'Liban' },
  { iso2: 'JO', dial: '+962', name: 'Jordanie' },
  { iso2: 'IL', dial: '+972', name: 'Israël' },
  { iso2: 'IQ', dial: '+964', name: 'Irak' },
  { iso2: 'IR', dial: '+98',  name: 'Iran' },
  { iso2: 'AU', dial: '+61',  name: 'Australie' },
  { iso2: 'NZ', dial: '+64',  name: 'Nouvelle-Zélande' },
].sort((a, b) => a.name.localeCompare(b.name, 'fr'))
